version: '3.4'
services:
  openway-tasklist-share:
    image: docker.iopenway.it/openway-tasklist/share:${project.version}
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: ${acs.host}
      REPO_PORT: ${acs.port}
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
